# Machine Learning Platform Engineer - Desafio Punk API
# Doc: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Configura recursos AWS para desafio PunkAPI

# Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters:
  KinesisStreamName:
    Type: String
    Default: "PunkAPIKinesisStream"
    Description: "Define o nome para Kinesis Data Stream."
  CliLambdaInterval:
    Type: String
    # Doc: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#RateExpressions
    Default: rate(1 minute)
    Description: "Intervalo de tempo de chamada da função para consulta da API."
  FirehoseInterval: # sec
    Type: Number
    Default: "300" # 5min
    Description: "Intervalo de tempo para buffering do firehose."
  FirehoseSize: # MB
    Type: Number
    Default: "30"
    Description: "Intervalo de tempo para buffering do firehose."

# Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # LogicalID

  ########################################################################
  # Cria AWS Kinesis Data Stream  
  ########################################################################
  KinesisStream:
    # Doc https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/aws-resource-kinesis-stream.html
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Ref KinesisStreamName
      ShardCount: 1
    # Ref: https://serverlessland.com/patterns/kinesis-lambda

  ########################################################################
  # Cria uma regra de acesso para Lambda escrever no Kinesis e no log
  ########################################################################
  LambdaPinkApiCliRole:
    # Doc: https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
              # Link: https://docs.aws.amazon.com/general/latest/gr/ak.html
            Action: 
              - "sts:AssumeRole"
              # Ref: https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html 
              # Returns a set of temporary security credentials that you can use to access AWS resources that you might not normally have access to.
      Policies:
        - PolicyName: LogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Effect: Allow
              Resource: 
                - "arn:aws:logs:*:*:*"
        - PolicyName: KinesisPutRecordPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
                - kinesis:PutRecord
                # Kinesis actions: https://docs.aws.amazon.com/kinesis/latest/APIReference/API_Operations.html
              Effect: Allow
              Resource:
                - !GetAtt KinesisStream.Arn
                - !Sub
                  - ${Arn}/*
                  - { Arn: !GetAtt KinesisStream.Arn }
      RoleName: "LambdaPinkApiCliRole"
      Description: "Cria uma regra para permitir a função lambda a enviar dados para o Kinesis e para o log."  

  ########################################################################
  # Função Lambda para consumir API
  ########################################################################
  PunkAPICliLambda:
    # Doc: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: punkapi_cli/
      Handler: app.lambda_handler
      Runtime: python3.8
      FunctionName: PunkAPICliLambdaFunction
      VersionDescription: "0.01"
      Description: "Função lambda que consome endpoint da Punk API para obter bebidas aleatórias."
      Environment:
        Variables:
          KinesisStreamName: !Ref KinesisStreamName
      # Events:
      #   CheckWebsiteScheduledEvent:
      #     Type: Schedule
      #     Properties:
      #       # Must follow this syntax: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
      #       Schedule: rate(5 minutes)
      # Permite enviar dados para Kinesis e escrever no log
      Role: !GetAtt LambdaPinkApiCliRole.Arn

  ########################################################################
  # Regra para ativar função lambda
  ########################################################################
  ScheduledEventIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                  - "events.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: LogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Effect: Allow
              Resource: 
                - "arn:aws:logs:*:*:*"
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
                - lambda:InvokeFunction
              Effect: Allow
              Resource:
                - !Ref PunkAPICliLambda

  ########################################################################
  # Evento de chamada da função para cada 5min
  ########################################################################
  # Ref: https://blog.shikisoft.com/3-ways-to-schedule-aws-lambda-and-step-functions-state-machines/
  # Ref: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
  ScheduledEventRule:
    # Doc: https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html
    Type: "AWS::Events::Rule"
    Properties:
      Description: "Evento programado para chamar função de consulta da API a cada 5 minutos."
      ScheduleExpression: !Ref CliLambdaInterval
      State: "DISABLED"
      Targets:
        - Arn: !Ref PunkAPICliLambda
          Id: ScheduledEventRuleLambdaID
          RoleArn: !GetAtt ScheduledEventIAMRole.Arn

  ########################################################################
  # Cria repositório para dados Raw
  ########################################################################
  RawDataBucket:
    # Doc: https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
    Type: AWS::S3::Bucket
    Properties:
      BucketName: punkapiraw
      AccessControl: BucketOwnerFullControl
  
  ########################################################################
  # Cria repositório para dados cleaned
  ########################################################################
  CleanedDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: punkapicleaned
      AccessControl: BucketOwnerFullControl
  
  ########################################################################
  # Cria regra para os lambdas poderem inserir dados no log
  ########################################################################
  LambdaCleanRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
              # Link: https://docs.aws.amazon.com/general/latest/gr/ak.html
            Action: 
              - "sts:AssumeRole"
      Policies:
        - PolicyName: LogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Effect: Allow
              Resource: 
                - "arn:aws:logs:*:*:*"
              # ref: https://stackoverflow.com/questions/37382889/cant-get-aws-lambda-function-to-log-text-output-to-cloudwatch    
      RoleName: "LambdaCleanRole"
      Description: "Cria uma regra para permitir a função lambda a enviar dados para o log."   
  
  ########################################################################
  # Função Lambda para resgatar campos de interesse (clean)
  ########################################################################
  PunkAPICleanLambda:
    # Doc: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: punkapi_clean/
      Handler: app.lambda_handler
      Runtime: python3.8
      FunctionName: PunkAPICleanLambdaFunction
      VersionDescription: "0.01"
      Description: "Função lambda que resgata os campos de interesse."
      Role: !GetAtt LambdaCleanRole.Arn
      Timeout: 30
  
  ########################################################################
  # Cria regra de acesso do Firehose para Kinesis Stream
  ########################################################################
  FirehoseRole:
    # Doc: https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "firehose.amazonaws.com"
              # Link: https://docs.aws.amazon.com/general/latest/gr/ak.html
            Action: 
              - "sts:AssumeRole"
              # Ref: https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html 
              # Returns a set of temporary security credentials that you can use to access AWS resources that you might not normally have access to.
      Policies:
        - PolicyName: KinesisSourceStreamPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
                - kinesis:*
                # # Doc: https://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetRecords.html
                # - kinesis:GetRecords
                # # Doc: https://docs.aws.amazon.com/kinesis/latest/APIReference/API_DescribeStream.html
                # - kinesis:DescribeStream
                # Kinesis actions: https://docs.aws.amazon.com/kinesis/latest/APIReference/API_Operations.html                
              Effect: Allow
              Resource:
                - !GetAtt KinesisStream.Arn
                - !Sub
                  - ${Arn}/*
                  - { Arn: !GetAtt KinesisStream.Arn }
        - PolicyName: S3WritePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
                - s3:PutObject
              Effect: Allow
              Resource:
                - !GetAtt RawDataBucket.Arn
                - !Sub
                  - ${Arn}/*
                  - { Arn: !GetAtt RawDataBucket.Arn }
                - !GetAtt CleanedDataBucket.Arn
                - !Sub
                  - ${Arn}/*
                  - { Arn: !GetAtt CleanedDataBucket.Arn }
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
                - lambda:InvokeFunction
              Effect: Allow
              Resource:
                - !GetAtt PunkAPICleanLambda.Arn
      RoleName: FirehoseRole
      Description: "Cria uma regra para permitir o firehose acessar dados do Kinesis e escrever no S3."

  ########################################################################
  # Cria Firehose para ingerir dados no S3
  ########################################################################
  FirehoseStream:
    # Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesisfirehose-deliverystream.html
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: PunkAPIFirehose
      DeliveryStreamType: KinesisStreamAsSource
      # Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-kinesisstreamsourceconfiguration.html
      KinesisStreamSourceConfiguration:
        KinesisStreamARN: !GetAtt KinesisStream.Arn
        RoleARN: !GetAtt FirehoseRole.Arn
      # Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-s3destinationconfiguration.html
      # S3DestinationConfiguration:
      #   BucketArn: !GetAtt RawDataBucket.Arn
      #   BufferingHints:
      #     IntervalInSeconds: 60
      #     SizeInMBs: 3
      #   RoleARN: !GetAtt FirehoseRole.Arn
      # Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-extendeds3destinationconfiguration.html
      ExtendedS3DestinationConfiguration:
        BucketARN: !GetAtt CleanedDataBucket.Arn
        CompressionFormat: GZIP
        RoleARN: !GetAtt FirehoseRole.Arn
        BufferingHints:
          IntervalInSeconds: !Ref FirehoseInterval
          SizeInMBs: !Ref FirehoseSize
        # Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-processingconfiguration.html
        ProcessingConfiguration:
          Enabled: true
          Processors:
            - Type: Lambda
              Parameters:
                - ParameterName: LambdaArn
                  ParameterValue: !GetAtt PunkAPICleanLambda.Arn
        S3BackupMode: Enabled
        S3BackupConfiguration:
          BucketARN: !GetAtt RawDataBucket.Arn
          CompressionFormat: GZIP
          RoleARN: !GetAtt FirehoseRole.Arn
          BufferingHints:
            IntervalInSeconds: !Ref FirehoseInterval
            SizeInMBs: !Ref FirehoseSize

  ########################################################################
  # Cria Database para armazenar os metadados identificados pelo crawler
  ########################################################################
  DatabaseCleanGlue:
    # Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-database-databaseinput.html
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: punkcleandb
        Description: "Banco com informações de metadados identificados pelo crawler."

  ########################################################################
  # Cria permissionamento para crawler acessar informações do S3
  ########################################################################
  CrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: LogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Effect: Allow
              Resource: 
                - "arn:aws:logs:*:*:*"
        - PolicyName: S3GluePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
                - s3:*
              Effect: Allow
              Resource:
                - !GetAtt CleanedDataBucket.Arn
                - !Sub
                  - ${Arn}/*
                  - { Arn: !GetAtt CleanedDataBucket.Arn }
        - PolicyName: GluePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
                - glue:*
              Effect: Allow
              Resource:
                - "arn:aws:glue:*:*:*"

  ########################################################################
  # Cria Crawler para identificar schema dos dados limpos 
  ########################################################################
  CrawlerCleanGlue:
    # Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-crawler.html
    # Ref: https://github.com/subkanthi/aws-glue-crawler/blob/master/glue-templates/glue-s3-crawler.yaml
    Type: AWS::Glue::Crawler
    Properties:
      Name: CrawlerCleanGlue
      Description: "Permite identificar o schema dos dados limpos."
      Role: !GetAtt CrawlerRole.Arn
      DatabaseName: !Ref DatabaseCleanGlue
      Targets: 
        S3Targets:
          - Path: !Ref CleanedDataBucket
          - Exclusions: 
            - "*failed"
      RecrawlPolicy: 
        RecrawlBehavior: "CRAWL_EVERYTHING"
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      TablePrefix: "punk-api-clean-"