# Machine Learning Platform Engineer - Desafio Punk API
# Doc: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Configura recursos AWS para desafio PunkAPI

# Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters:
  KinesisStreamName:
    Type: String
    Default: "PunkAPIKinesisStream"
    Description: "Define o nome para Kinesis Data Stream."

# Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # LogicalID
  # Função Lambda para consumir API
  PunkAPICliLambda:
    # Doc: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: punkapi_cli/
      Handler: app.lambda_handler
      Runtime: python3.8
      FunctionName: PunkAPICliLambdaFunction
      VersionDescription: "0.01"
      Description: "Função lambda que consome endpoint da Punk API para obter bebidas aleatórias."
      Environment:
        Variables:
          KinesisStreamName: !Ref KinesisStreamName
      # Permite enviar dados para Kinesis
      Policies: 
        - KinesisPuRecord
        - Version: "2012-10-17"
          Statement:
            Action:
              - kinesis:PutRecord
            Effect: Allow
            Resource:
              - !Ref KinesisStream
            Effect: Allow
            Resource: 
              Action:
                - kinesis:PutRecord
  # Cria AWS Kinesis Data Stream  
  KinesisStream:
    # Doc https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/aws-resource-kinesis-stream.html
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Ref KinesisStreamName
      ShardCount: 1
    # Ref: https://serverlessland.com/patterns/kinesis-lambda