version=0.1

[default.deploy.parameters]
stack_name="punk-api"
s3_bucket="github-action-aws"
s3_prefix="YYYY/MM/DD"
region="sa-east-1"
confirm_changeset=false
capabilities="CAPABILITY_IAM"
tags="github"