name: Github Action para publicar recursos na AWS

on:
  push:
    branches:
      - gaction_aws
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      SAM_CLI_TELEMETRY: 0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # São Paulo 
          aws-region: ${{ secrets.AWS_REGION }}     
      # sam build 
      - run: sam build --use-container --template ./sam-aws/sam-aws-punkapi.yml --base-dir ./sam-aws --build-dir ./sam-aws
      # sam deploy
      # config: https://github.com/aws/aws-sam-cli/issues/2747
      - run: sam deploy --no-confirm-changeset 
                        --no-fail-on-empty-changeset 
                        --template ./sam-aws/sam-aws-punkapi.yml 
                        --stack-name punk-api-stack
                        --s3-bucket github-action-aws
                        --region ${{ secrets.AWS_REGION }} 
                        --capabilities CAPABILITY_IAM

## Referência: https://aws.amazon.com/blogs/compute/using-github-actions-to-deploy-serverless-applications/